logLevel: DEBUG

api:
  dashboard: true
  # api: insecure

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  traefik:
    address: ":8080"


providers:
  file:
    filename: /etc/traefik/dynamic.yml
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    # Do not expose containers unless explicitly told so
    exposedByDefault: true